---
title: "Measles susceptibility in Edinburgh"
author: "Group 12"
execute: 
  echo: false
  eval: true
number-sections: true
format:
  html:
    embed-resources: true
editor_options: 
  chunk_output_type: console
---

```{r}
#| echo: false
#| warning: false
#| message: false
library(readr)
library(ggplot2)
library(ggfortify)
library(tidyverse)
library(tidymodels)
library(gt)
library(MASS)
library(patchwork)
library(moderndive)
```

# Introduction {#sec-intro}

Data on Measles susceptibility in primary school children, between 1998 and 2012, in the 101 intermediate zones(IZ) in Edinburgh has been recorded. The IZ are small geographical areas that contain, on average, 4000 residents.

The data set DAProject16.csv contains the following data:

-   Y- The number of pre-school children susceptible to measles in a given IZ

-   N- The total number of pre-school children in a given IZ

-   Year- The year the data was collected

We are interested in whether Edinburgh exhibited a change in measles susceptibility following the retraction of the Wakefield article. We are also interested in if the change, if any, in measles susceptibility occurred in 2004 alongside the articles retraction.

# Exploratory Analysis {#sec-EA}

# Formal Analysis {#sec-FA}

We fit a normal linear model with...

# Conclusions {#sec-con}
